/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:86d20783-2029-457e-88e3-e503fcd720fd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_A8VETefWg",
    "aws_user_pools_web_client_id": "3ocb6h3bc9t73ts1mq6t28l0gh",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://4vxxdhfgizc3tbtt3o3av7ub4i.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
